package fr.gette.hciexplorer.hciSpecification;

public enum MajorServiceClass {
    LIMITED_DISCOVERABLE_MODE,
    POSITIONING, // Location identification
    NETWORKING, // LAN, Ad hoc, ...
    RENDERING, // Printing, Speaker, ...
    CAPTURING, // Scanner, Microphone, ...
    OBJECT_TRANSFER, // v-Inbox, v-Folder, ...
    AUDIO, // Speaker, Microphone, Headset service, ...
    TELEPHONY, // Cordless telephony, Modem, Headset service, ...
    INFORMATION; // WEB-server, WAP-server, ...
}
